/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AdminCarnet: () => import('#controllers/admin_carnet_controller'),
  AuthEstudiante: () => import('#controllers/auth_estudiante_controller'),
  AuthPanel: () => import('#controllers/auth_panel_controller'),
  Carnet: () => import('#controllers/carnet_controller'),
  Consulta: () => import('#controllers/consulta_controller'),
}
